allowBuilds:
  '@bufbuild/buf': false
  '@google/genai': false
  '@prisma/client': false
  '@prisma/engines': false
  better-sqlite3: false
  esbuild: true
  lefthook: true
  playwright: true
  prisma: false
  protobufjs: false
