/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppSubappsIndexRouteImport } from './routes/_app/subapps/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppSubappIdSplatRouteImport } from './routes/app/$subappId/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent/stream'
import { Route as ApiAgentAnswerRouteImport } from './routes/api/agent/answer'
import { Route as AppSubappsSubappIdRouteImport } from './routes/_app/subapps/$subappId'
import { Route as AppDashboardDashboardIdRouteImport } from './routes/_app/dashboard/$dashboardId'
import { Route as AppAppsSubappIdRouteImport } from './routes/_app/apps/$subappId'
import { Route as ApiHooksSubappIdSplatRouteImport } from './routes/api/hooks/$subappId/$'
import { Route as ApiSubappsSubappIdWidgetWidgetIdRouteImport } from './routes/api/subapps/$subappId/widget/$widgetId'
import { Route as ApiSubappsSubappIdStorageSplatRouteImport } from './routes/api/subapps/$subappId/storage/$'
import { Route as ApiSubappsSubappIdRpcSplatRouteImport } from './routes/api/subapps/$subappId/rpc/$'
import { Route as ApiSubappsSubappIdAppSplatRouteImport } from './routes/api/subapps/$subappId/app/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSubappsIndexRoute = AppSubappsIndexRouteImport.update({
  id: '/subapps/',
  path: '/subapps/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubappIdSplatRoute = AppSubappIdSplatRouteImport.update({
  id: '/app/$subappId/$',
  path: '/app/$subappId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent/stream',
  path: '/api/agent/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAnswerRoute = ApiAgentAnswerRouteImport.update({
  id: '/api/agent/answer',
  path: '/api/agent/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubappsSubappIdRoute = AppSubappsSubappIdRouteImport.update({
  id: '/subapps/$subappId',
  path: '/subapps/$subappId',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardDashboardIdRoute = AppDashboardDashboardIdRouteImport.update({
  id: '/dashboard/$dashboardId',
  path: '/dashboard/$dashboardId',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsSubappIdRoute = AppAppsSubappIdRouteImport.update({
  id: '/apps/$subappId',
  path: '/apps/$subappId',
  getParentRoute: () => AppRoute,
} as any)
const ApiHooksSubappIdSplatRoute = ApiHooksSubappIdSplatRouteImport.update({
  id: '/api/hooks/$subappId/$',
  path: '/api/hooks/$subappId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubappsSubappIdWidgetWidgetIdRoute =
  ApiSubappsSubappIdWidgetWidgetIdRouteImport.update({
    id: '/api/subapps/$subappId/widget/$widgetId',
    path: '/api/subapps/$subappId/widget/$widgetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubappsSubappIdStorageSplatRoute =
  ApiSubappsSubappIdStorageSplatRouteImport.update({
    id: '/api/subapps/$subappId/storage/$',
    path: '/api/subapps/$subappId/storage/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubappsSubappIdRpcSplatRoute =
  ApiSubappsSubappIdRpcSplatRouteImport.update({
    id: '/api/subapps/$subappId/rpc/$',
    path: '/api/subapps/$subappId/rpc/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubappsSubappIdAppSplatRoute =
  ApiSubappsSubappIdAppSplatRouteImport.update({
    id: '/api/subapps/$subappId/app/$',
    path: '/api/subapps/$subappId/app/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/agent': typeof AppAgentRoute
  '/settings': typeof AppSettingsRoute
  '/apps/$subappId': typeof AppAppsSubappIdRoute
  '/dashboard/$dashboardId': typeof AppDashboardDashboardIdRoute
  '/subapps/$subappId': typeof AppSubappsSubappIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$subappId/$': typeof AppSubappIdSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/subapps/': typeof AppSubappsIndexRoute
  '/api/hooks/$subappId/$': typeof ApiHooksSubappIdSplatRoute
  '/api/subapps/$subappId/app/$': typeof ApiSubappsSubappIdAppSplatRoute
  '/api/subapps/$subappId/rpc/$': typeof ApiSubappsSubappIdRpcSplatRoute
  '/api/subapps/$subappId/storage/$': typeof ApiSubappsSubappIdStorageSplatRoute
  '/api/subapps/$subappId/widget/$widgetId': typeof ApiSubappsSubappIdWidgetWidgetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/agent': typeof AppAgentRoute
  '/settings': typeof AppSettingsRoute
  '/apps/$subappId': typeof AppAppsSubappIdRoute
  '/dashboard/$dashboardId': typeof AppDashboardDashboardIdRoute
  '/subapps/$subappId': typeof AppSubappsSubappIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$subappId/$': typeof AppSubappIdSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/subapps': typeof AppSubappsIndexRoute
  '/api/hooks/$subappId/$': typeof ApiHooksSubappIdSplatRoute
  '/api/subapps/$subappId/app/$': typeof ApiSubappsSubappIdAppSplatRoute
  '/api/subapps/$subappId/rpc/$': typeof ApiSubappsSubappIdRpcSplatRoute
  '/api/subapps/$subappId/storage/$': typeof ApiSubappsSubappIdStorageSplatRoute
  '/api/subapps/$subappId/widget/$widgetId': typeof ApiSubappsSubappIdWidgetWidgetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/apps/$subappId': typeof AppAppsSubappIdRoute
  '/_app/dashboard/$dashboardId': typeof AppDashboardDashboardIdRoute
  '/_app/subapps/$subappId': typeof AppSubappsSubappIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$subappId/$': typeof AppSubappIdSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/subapps/': typeof AppSubappsIndexRoute
  '/api/hooks/$subappId/$': typeof ApiHooksSubappIdSplatRoute
  '/api/subapps/$subappId/app/$': typeof ApiSubappsSubappIdAppSplatRoute
  '/api/subapps/$subappId/rpc/$': typeof ApiSubappsSubappIdRpcSplatRoute
  '/api/subapps/$subappId/storage/$': typeof ApiSubappsSubappIdStorageSplatRoute
  '/api/subapps/$subappId/widget/$widgetId': typeof ApiSubappsSubappIdWidgetWidgetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/agent'
    | '/settings'
    | '/apps/$subappId'
    | '/dashboard/$dashboardId'
    | '/subapps/$subappId'
    | '/api/agent/answer'
    | '/api/agent/stream'
    | '/api/auth/$'
    | '/app/$subappId/$'
    | '/dashboard/'
    | '/subapps/'
    | '/api/hooks/$subappId/$'
    | '/api/subapps/$subappId/app/$'
    | '/api/subapps/$subappId/rpc/$'
    | '/api/subapps/$subappId/storage/$'
    | '/api/subapps/$subappId/widget/$widgetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/agent'
    | '/settings'
    | '/apps/$subappId'
    | '/dashboard/$dashboardId'
    | '/subapps/$subappId'
    | '/api/agent/answer'
    | '/api/agent/stream'
    | '/api/auth/$'
    | '/app/$subappId/$'
    | '/dashboard'
    | '/subapps'
    | '/api/hooks/$subappId/$'
    | '/api/subapps/$subappId/app/$'
    | '/api/subapps/$subappId/rpc/$'
    | '/api/subapps/$subappId/storage/$'
    | '/api/subapps/$subappId/widget/$widgetId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app'
    | '/login'
    | '/_app/agent'
    | '/_app/settings'
    | '/_app/apps/$subappId'
    | '/_app/dashboard/$dashboardId'
    | '/_app/subapps/$subappId'
    | '/api/agent/answer'
    | '/api/agent/stream'
    | '/api/auth/$'
    | '/app/$subappId/$'
    | '/_app/dashboard/'
    | '/_app/subapps/'
    | '/api/hooks/$subappId/$'
    | '/api/subapps/$subappId/app/$'
    | '/api/subapps/$subappId/rpc/$'
    | '/api/subapps/$subappId/storage/$'
    | '/api/subapps/$subappId/widget/$widgetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAgentAnswerRoute: typeof ApiAgentAnswerRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppSubappIdSplatRoute: typeof AppSubappIdSplatRoute
  ApiHooksSubappIdSplatRoute: typeof ApiHooksSubappIdSplatRoute
  ApiSubappsSubappIdAppSplatRoute: typeof ApiSubappsSubappIdAppSplatRoute
  ApiSubappsSubappIdRpcSplatRoute: typeof ApiSubappsSubappIdRpcSplatRoute
  ApiSubappsSubappIdStorageSplatRoute: typeof ApiSubappsSubappIdStorageSplatRoute
  ApiSubappsSubappIdWidgetWidgetIdRoute: typeof ApiSubappsSubappIdWidgetWidgetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subapps/': {
      id: '/_app/subapps/'
      path: '/subapps'
      fullPath: '/subapps/'
      preLoaderRoute: typeof AppSubappsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$subappId/$': {
      id: '/app/$subappId/$'
      path: '/app/$subappId/$'
      fullPath: '/app/$subappId/$'
      preLoaderRoute: typeof AppSubappIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stream': {
      id: '/api/agent/stream'
      path: '/api/agent/stream'
      fullPath: '/api/agent/stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/answer': {
      id: '/api/agent/answer'
      path: '/api/agent/answer'
      fullPath: '/api/agent/answer'
      preLoaderRoute: typeof ApiAgentAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/subapps/$subappId': {
      id: '/_app/subapps/$subappId'
      path: '/subapps/$subappId'
      fullPath: '/subapps/$subappId'
      preLoaderRoute: typeof AppSubappsSubappIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/$dashboardId': {
      id: '/_app/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/dashboard/$dashboardId'
      preLoaderRoute: typeof AppDashboardDashboardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$subappId': {
      id: '/_app/apps/$subappId'
      path: '/apps/$subappId'
      fullPath: '/apps/$subappId'
      preLoaderRoute: typeof AppAppsSubappIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/hooks/$subappId/$': {
      id: '/api/hooks/$subappId/$'
      path: '/api/hooks/$subappId/$'
      fullPath: '/api/hooks/$subappId/$'
      preLoaderRoute: typeof ApiHooksSubappIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subapps/$subappId/widget/$widgetId': {
      id: '/api/subapps/$subappId/widget/$widgetId'
      path: '/api/subapps/$subappId/widget/$widgetId'
      fullPath: '/api/subapps/$subappId/widget/$widgetId'
      preLoaderRoute: typeof ApiSubappsSubappIdWidgetWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subapps/$subappId/storage/$': {
      id: '/api/subapps/$subappId/storage/$'
      path: '/api/subapps/$subappId/storage/$'
      fullPath: '/api/subapps/$subappId/storage/$'
      preLoaderRoute: typeof ApiSubappsSubappIdStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subapps/$subappId/rpc/$': {
      id: '/api/subapps/$subappId/rpc/$'
      path: '/api/subapps/$subappId/rpc/$'
      fullPath: '/api/subapps/$subappId/rpc/$'
      preLoaderRoute: typeof ApiSubappsSubappIdRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subapps/$subappId/app/$': {
      id: '/api/subapps/$subappId/app/$'
      path: '/api/subapps/$subappId/app/$'
      fullPath: '/api/subapps/$subappId/app/$'
      preLoaderRoute: typeof ApiSubappsSubappIdAppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAppsSubappIdRoute: typeof AppAppsSubappIdRoute
  AppDashboardDashboardIdRoute: typeof AppDashboardDashboardIdRoute
  AppSubappsSubappIdRoute: typeof AppSubappsSubappIdRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppSubappsIndexRoute: typeof AppSubappsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAppsSubappIdRoute: AppAppsSubappIdRoute,
  AppDashboardDashboardIdRoute: AppDashboardDashboardIdRoute,
  AppSubappsSubappIdRoute: AppSubappsSubappIdRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppSubappsIndexRoute: AppSubappsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAgentAnswerRoute: ApiAgentAnswerRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppSubappIdSplatRoute: AppSubappIdSplatRoute,
  ApiHooksSubappIdSplatRoute: ApiHooksSubappIdSplatRoute,
  ApiSubappsSubappIdAppSplatRoute: ApiSubappsSubappIdAppSplatRoute,
  ApiSubappsSubappIdRpcSplatRoute: ApiSubappsSubappIdRpcSplatRoute,
  ApiSubappsSubappIdStorageSplatRoute: ApiSubappsSubappIdStorageSplatRoute,
  ApiSubappsSubappIdWidgetWidgetIdRoute: ApiSubappsSubappIdWidgetWidgetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
