/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardsRouteImport } from './routes/_app/dashboards'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppAppIdSplatRouteImport } from './routes/app/$appId/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent/stream'
import { Route as ApiAgentAnswerRouteImport } from './routes/api/agent/answer'
import { Route as AppDashboardDashboardIdRouteImport } from './routes/_app/dashboard/$dashboardId'
import { Route as AppAppsAppIdIndexRouteImport } from './routes/_app/apps/$appId/index'
import { Route as ApiHooksAppIdSplatRouteImport } from './routes/api/hooks/$appId/$'
import { Route as AppAppsAppIdManageRouteImport } from './routes/_app/apps/$appId/manage'
import { Route as ApiAppsAppIdWidgetWidgetIdRouteImport } from './routes/api/apps/$appId/widget/$widgetId'
import { Route as ApiAppsAppIdStorageSplatRouteImport } from './routes/api/apps/$appId/storage/$'
import { Route as ApiAppsAppIdRpcSplatRouteImport } from './routes/api/apps/$appId/rpc/$'
import { Route as ApiAppsAppIdAppSplatRouteImport } from './routes/api/apps/$appId/app/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppIdSplatRoute = AppAppIdSplatRouteImport.update({
  id: '/app/$appId/$',
  path: '/app/$appId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent/stream',
  path: '/api/agent/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAnswerRoute = ApiAgentAnswerRouteImport.update({
  id: '/api/agent/answer',
  path: '/api/agent/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardDashboardIdRoute = AppDashboardDashboardIdRouteImport.update({
  id: '/dashboard/$dashboardId',
  path: '/dashboard/$dashboardId',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdIndexRoute = AppAppsAppIdIndexRouteImport.update({
  id: '/apps/$appId/',
  path: '/apps/$appId/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHooksAppIdSplatRoute = ApiHooksAppIdSplatRouteImport.update({
  id: '/api/hooks/$appId/$',
  path: '/api/hooks/$appId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsAppIdManageRoute = AppAppsAppIdManageRouteImport.update({
  id: '/apps/$appId/manage',
  path: '/apps/$appId/manage',
  getParentRoute: () => AppRoute,
} as any)
const ApiAppsAppIdWidgetWidgetIdRoute =
  ApiAppsAppIdWidgetWidgetIdRouteImport.update({
    id: '/api/apps/$appId/widget/$widgetId',
    path: '/api/apps/$appId/widget/$widgetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAppsAppIdStorageSplatRoute =
  ApiAppsAppIdStorageSplatRouteImport.update({
    id: '/api/apps/$appId/storage/$',
    path: '/api/apps/$appId/storage/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAppsAppIdRpcSplatRoute = ApiAppsAppIdRpcSplatRouteImport.update({
  id: '/api/apps/$appId/rpc/$',
  path: '/api/apps/$appId/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppsAppIdAppSplatRoute = ApiAppsAppIdAppSplatRouteImport.update({
  id: '/api/apps/$appId/app/$',
  path: '/api/apps/$appId/app/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/agent': typeof AppAgentRoute
  '/dashboards': typeof AppDashboardsRoute
  '/settings': typeof AppSettingsRoute
  '/dashboard/$dashboardId': typeof AppDashboardDashboardIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$appId/$': typeof AppAppIdSplatRoute
  '/apps/': typeof AppAppsIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/apps/$appId/manage': typeof AppAppsAppIdManageRoute
  '/api/hooks/$appId/$': typeof ApiHooksAppIdSplatRoute
  '/apps/$appId/': typeof AppAppsAppIdIndexRoute
  '/api/apps/$appId/app/$': typeof ApiAppsAppIdAppSplatRoute
  '/api/apps/$appId/rpc/$': typeof ApiAppsAppIdRpcSplatRoute
  '/api/apps/$appId/storage/$': typeof ApiAppsAppIdStorageSplatRoute
  '/api/apps/$appId/widget/$widgetId': typeof ApiAppsAppIdWidgetWidgetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/agent': typeof AppAgentRoute
  '/dashboards': typeof AppDashboardsRoute
  '/settings': typeof AppSettingsRoute
  '/dashboard/$dashboardId': typeof AppDashboardDashboardIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$appId/$': typeof AppAppIdSplatRoute
  '/apps': typeof AppAppsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/apps/$appId/manage': typeof AppAppsAppIdManageRoute
  '/api/hooks/$appId/$': typeof ApiHooksAppIdSplatRoute
  '/apps/$appId': typeof AppAppsAppIdIndexRoute
  '/api/apps/$appId/app/$': typeof ApiAppsAppIdAppSplatRoute
  '/api/apps/$appId/rpc/$': typeof ApiAppsAppIdRpcSplatRoute
  '/api/apps/$appId/storage/$': typeof ApiAppsAppIdStorageSplatRoute
  '/api/apps/$appId/widget/$widgetId': typeof ApiAppsAppIdWidgetWidgetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/dashboard/$dashboardId': typeof AppDashboardDashboardIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$appId/$': typeof AppAppIdSplatRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/apps/$appId/manage': typeof AppAppsAppIdManageRoute
  '/api/hooks/$appId/$': typeof ApiHooksAppIdSplatRoute
  '/_app/apps/$appId/': typeof AppAppsAppIdIndexRoute
  '/api/apps/$appId/app/$': typeof ApiAppsAppIdAppSplatRoute
  '/api/apps/$appId/rpc/$': typeof ApiAppsAppIdRpcSplatRoute
  '/api/apps/$appId/storage/$': typeof ApiAppsAppIdStorageSplatRoute
  '/api/apps/$appId/widget/$widgetId': typeof ApiAppsAppIdWidgetWidgetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/agent'
    | '/dashboards'
    | '/settings'
    | '/dashboard/$dashboardId'
    | '/api/agent/answer'
    | '/api/agent/stream'
    | '/api/auth/$'
    | '/app/$appId/$'
    | '/apps/'
    | '/dashboard/'
    | '/apps/$appId/manage'
    | '/api/hooks/$appId/$'
    | '/apps/$appId/'
    | '/api/apps/$appId/app/$'
    | '/api/apps/$appId/rpc/$'
    | '/api/apps/$appId/storage/$'
    | '/api/apps/$appId/widget/$widgetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/agent'
    | '/dashboards'
    | '/settings'
    | '/dashboard/$dashboardId'
    | '/api/agent/answer'
    | '/api/agent/stream'
    | '/api/auth/$'
    | '/app/$appId/$'
    | '/apps'
    | '/dashboard'
    | '/apps/$appId/manage'
    | '/api/hooks/$appId/$'
    | '/apps/$appId'
    | '/api/apps/$appId/app/$'
    | '/api/apps/$appId/rpc/$'
    | '/api/apps/$appId/storage/$'
    | '/api/apps/$appId/widget/$widgetId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app'
    | '/login'
    | '/_app/agent'
    | '/_app/dashboards'
    | '/_app/settings'
    | '/_app/dashboard/$dashboardId'
    | '/api/agent/answer'
    | '/api/agent/stream'
    | '/api/auth/$'
    | '/app/$appId/$'
    | '/_app/apps/'
    | '/_app/dashboard/'
    | '/_app/apps/$appId/manage'
    | '/api/hooks/$appId/$'
    | '/_app/apps/$appId/'
    | '/api/apps/$appId/app/$'
    | '/api/apps/$appId/rpc/$'
    | '/api/apps/$appId/storage/$'
    | '/api/apps/$appId/widget/$widgetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAgentAnswerRoute: typeof ApiAgentAnswerRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppAppIdSplatRoute: typeof AppAppIdSplatRoute
  ApiHooksAppIdSplatRoute: typeof ApiHooksAppIdSplatRoute
  ApiAppsAppIdAppSplatRoute: typeof ApiAppsAppIdAppSplatRoute
  ApiAppsAppIdRpcSplatRoute: typeof ApiAppsAppIdRpcSplatRoute
  ApiAppsAppIdStorageSplatRoute: typeof ApiAppsAppIdStorageSplatRoute
  ApiAppsAppIdWidgetWidgetIdRoute: typeof ApiAppsAppIdWidgetWidgetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$appId/$': {
      id: '/app/$appId/$'
      path: '/app/$appId/$'
      fullPath: '/app/$appId/$'
      preLoaderRoute: typeof AppAppIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stream': {
      id: '/api/agent/stream'
      path: '/api/agent/stream'
      fullPath: '/api/agent/stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/answer': {
      id: '/api/agent/answer'
      path: '/api/agent/answer'
      fullPath: '/api/agent/answer'
      preLoaderRoute: typeof ApiAgentAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/$dashboardId': {
      id: '/_app/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/dashboard/$dashboardId'
      preLoaderRoute: typeof AppDashboardDashboardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId/': {
      id: '/_app/apps/$appId/'
      path: '/apps/$appId'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AppAppsAppIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/hooks/$appId/$': {
      id: '/api/hooks/$appId/$'
      path: '/api/hooks/$appId/$'
      fullPath: '/api/hooks/$appId/$'
      preLoaderRoute: typeof ApiHooksAppIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/$appId/manage': {
      id: '/_app/apps/$appId/manage'
      path: '/apps/$appId/manage'
      fullPath: '/apps/$appId/manage'
      preLoaderRoute: typeof AppAppsAppIdManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/apps/$appId/widget/$widgetId': {
      id: '/api/apps/$appId/widget/$widgetId'
      path: '/api/apps/$appId/widget/$widgetId'
      fullPath: '/api/apps/$appId/widget/$widgetId'
      preLoaderRoute: typeof ApiAppsAppIdWidgetWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$appId/storage/$': {
      id: '/api/apps/$appId/storage/$'
      path: '/api/apps/$appId/storage/$'
      fullPath: '/api/apps/$appId/storage/$'
      preLoaderRoute: typeof ApiAppsAppIdStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$appId/rpc/$': {
      id: '/api/apps/$appId/rpc/$'
      path: '/api/apps/$appId/rpc/$'
      fullPath: '/api/apps/$appId/rpc/$'
      preLoaderRoute: typeof ApiAppsAppIdRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$appId/app/$': {
      id: '/api/apps/$appId/app/$'
      path: '/api/apps/$appId/app/$'
      fullPath: '/api/apps/$appId/app/$'
      preLoaderRoute: typeof ApiAppsAppIdAppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppDashboardDashboardIdRoute: typeof AppDashboardDashboardIdRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppAppsAppIdManageRoute: typeof AppAppsAppIdManageRoute
  AppAppsAppIdIndexRoute: typeof AppAppsAppIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppDashboardDashboardIdRoute: AppDashboardDashboardIdRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppAppsAppIdManageRoute: AppAppsAppIdManageRoute,
  AppAppsAppIdIndexRoute: AppAppsAppIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAgentAnswerRoute: ApiAgentAnswerRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppAppIdSplatRoute: AppAppIdSplatRoute,
  ApiHooksAppIdSplatRoute: ApiHooksAppIdSplatRoute,
  ApiAppsAppIdAppSplatRoute: ApiAppsAppIdAppSplatRoute,
  ApiAppsAppIdRpcSplatRoute: ApiAppsAppIdRpcSplatRoute,
  ApiAppsAppIdStorageSplatRoute: ApiAppsAppIdStorageSplatRoute,
  ApiAppsAppIdWidgetWidgetIdRoute: ApiAppsAppIdWidgetWidgetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
